// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftfdwfidzpbutuiytwwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0ZmR3ZmlkenBidXR1aXl0d3duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTk0NjgsImV4cCI6MjA3MjMzNTQ2OH0.SbAP0uRksQ0e9w-vzemeR7AUriSQVa2VZ3iCtOwJGRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});